require:
  - rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/AndOr:
  Enabled: false
